- name: Configure Cisco Router
  hosts: router1
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios  # Specify Cisco OS
  tasks:
    - name: Add Entry to ACL 100
      cisco.ios.ios_config:
        lines:
          - ip access-list standard 10
          - 15 permit 192.168.50.0 0.0.0.255
        match: exact  # Ensure exact line matching
        replace: line  # Only replace if changes are made
        save_when: modified  # Save configuration if modified

- name: Backup Cisco IOS Configuration
  hosts: router1
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios  # Specify Cisco OS
    current_time: "{{ lookup('pipe', 'date +%Y%m%dT%H%M%S') }}"  # Get current date and time
  tasks:
    - name: Backup IOS Configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: config_output  # Register output from this task

    - name: Save Backup to File
      copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "/home/antonio/{{ inventory_hostname }}_backup_{{ current_time }}.cfg"

